// Code generated by protoc-gen-go.
// source: tvshow.proto
// DO NOT EDIT!

/*
Package tvshowpb is a generated protocol buffer package.

It is generated from these files:
	tvshow.proto

It has these top-level messages:
	Channel
	TvShow
*/
package tvshowpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Channel struct {
	Group      string `protobuf:"bytes,1,opt,name=group" json:"group,omitempty"`
	GroupTitle string `protobuf:"bytes,2,opt,name=group_title,json=groupTitle" json:"group_title,omitempty"`
	Name       string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Title      string `protobuf:"bytes,4,opt,name=title" json:"title,omitempty"`
}

func (m *Channel) Reset()                    { *m = Channel{} }
func (m *Channel) String() string            { return proto.CompactTextString(m) }
func (*Channel) ProtoMessage()               {}
func (*Channel) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Channel) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *Channel) GetGroupTitle() string {
	if m != nil {
		return m.GroupTitle
	}
	return ""
}

func (m *Channel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Channel) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type TvShow struct {
	Channel   *Channel `protobuf:"bytes,1,opt,name=channel" json:"channel,omitempty"`
	Desc      string   `protobuf:"bytes,2,opt,name=desc" json:"desc,omitempty"`
	Title     string   `protobuf:"bytes,3,opt,name=title" json:"title,omitempty"`
	Start     int32    `protobuf:"varint,4,opt,name=start" json:"start,omitempty"`
	End       int32    `protobuf:"varint,5,opt,name=end" json:"end,omitempty"`
	Duraction int32    `protobuf:"varint,6,opt,name=duraction" json:"duraction,omitempty"`
}

func (m *TvShow) Reset()                    { *m = TvShow{} }
func (m *TvShow) String() string            { return proto.CompactTextString(m) }
func (*TvShow) ProtoMessage()               {}
func (*TvShow) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TvShow) GetChannel() *Channel {
	if m != nil {
		return m.Channel
	}
	return nil
}

func (m *TvShow) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *TvShow) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *TvShow) GetStart() int32 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *TvShow) GetEnd() int32 {
	if m != nil {
		return m.End
	}
	return 0
}

func (m *TvShow) GetDuraction() int32 {
	if m != nil {
		return m.Duraction
	}
	return 0
}

func init() {
	proto.RegisterType((*Channel)(nil), "tvshowpb.Channel")
	proto.RegisterType((*TvShow)(nil), "tvshowpb.TvShow")
}

func init() { proto.RegisterFile("tvshow.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 211 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x4d, 0x6e, 0x83, 0x30,
	0x10, 0x85, 0x45, 0xf9, 0x2b, 0x43, 0x17, 0xed, 0xa8, 0x0b, 0x2f, 0x2a, 0xb5, 0x62, 0x55, 0xa9,
	0x12, 0x8b, 0xe6, 0x08, 0xb9, 0x01, 0x61, 0x1f, 0x19, 0xb0, 0x02, 0x11, 0xb1, 0x91, 0x31, 0x70,
	0xa2, 0xdc, 0x33, 0xf2, 0x18, 0x44, 0x76, 0xef, 0x7d, 0x1e, 0xcd, 0x37, 0x32, 0xbc, 0x99, 0x79,
	0x6c, 0xd5, 0x92, 0x0f, 0x5a, 0x19, 0x85, 0xaf, 0xae, 0x0d, 0x55, 0x76, 0x85, 0xf8, 0xd8, 0x72,
	0x29, 0x45, 0x8f, 0x9f, 0x10, 0x5e, 0xb4, 0x9a, 0x06, 0xe6, 0xfd, 0x78, 0xbf, 0x49, 0xe1, 0x0a,
	0x7e, 0x43, 0x4a, 0xe1, 0x6c, 0x3a, 0xd3, 0x0b, 0xf6, 0x42, 0x6f, 0x40, 0xa8, 0xb4, 0x04, 0x11,
	0x02, 0xc9, 0x6f, 0x82, 0xf9, 0xf4, 0x42, 0xd9, 0xae, 0x72, 0xe3, 0x81, 0x5b, 0x45, 0x25, 0xbb,
	0x7b, 0x10, 0x95, 0xf3, 0xa9, 0x55, 0x0b, 0xfe, 0x41, 0x5c, 0x3b, 0x2d, 0xd9, 0xd2, 0xff, 0x8f,
	0x7c, 0x3b, 0x29, 0x5f, 0xef, 0x29, 0xb6, 0x09, 0x6b, 0x68, 0xc4, 0x58, 0xaf, 0x6e, 0xca, 0xbb,
	0xc1, 0x7f, 0x32, 0x58, 0x3a, 0x1a, 0xae, 0x0d, 0x79, 0xc3, 0xc2, 0x15, 0x7c, 0x07, 0x5f, 0xc8,
	0x86, 0x85, 0xc4, 0x6c, 0xc4, 0x2f, 0x48, 0x9a, 0x49, 0xf3, 0xda, 0x74, 0x4a, 0xb2, 0x88, 0xf8,
	0x0e, 0xaa, 0x88, 0x3e, 0xe9, 0xf0, 0x08, 0x00, 0x00, 0xff, 0xff, 0xe2, 0xfc, 0x4f, 0x39, 0x34,
	0x01, 0x00, 0x00,
}
