language: go

go:
    - 1.8.1
    - master

services:
    - mongodb

before_install:
    - openssl aes-256-cbc -K $encrypted_b3ef398da182_key -iv $encrypted_b3ef398da182_iv -in client-secret.json.enc -out client-secret.json -d

script:
    - go test -v ./...

deploy:
    provider: gae
    keyfile: client-secret.json
    project: tvshow-165423
    on: master

